FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_SITE_URL=http://localhost:8088
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY=
ARG NEXT_PUBLIC_CONVERTER_MAX_FILE_SIZE_MB=20
ARG NEXT_PUBLIC_CONVERTER_MAX_FILES_PER_REQUEST=20
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_CONVERTER_MAX_FILE_SIZE_MB=$NEXT_PUBLIC_CONVERTER_MAX_FILE_SIZE_MB
ENV NEXT_PUBLIC_CONVERTER_MAX_FILES_PER_REQUEST=$NEXT_PUBLIC_CONVERTER_MAX_FILES_PER_REQUEST

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runner

COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
