"""Word → PDF converter using LibreOffice (soffice) subprocess."""

from __future__ import annotations

import asyncio
import subprocess
from dataclasses import dataclass
from pathlib import Path
from urllib.request import pathname2url

from fastapi import HTTPException


@dataclass(frozen=True)
class ConversionResult:
    output_path: Path
    file_name: str
    mime_type: str = "application/pdf"


async def convert_word_to_pdf(
    *,
    input_path: Path,
    output_dir: Path,
    profile_dir: Path,
    timeout_seconds: int = 120,
) -> ConversionResult:
    """Convert a Word document to PDF via LibreOffice headless mode.

    Runs ``soffice`` in a subprocess with a per-job user profile
    directory so multiple conversions don't collide.
    """
    user_installation = f"file://{pathname2url(str(profile_dir))}"

    cmd = [
        "soffice",
        "--headless",
        "--nologo",
        "--nofirststartwizard",
        "--convert-to", "pdf",
        "--outdir", str(output_dir),
        str(input_path),
    ]

    try:
        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env={"UserInstallation": user_installation},
        )
        _, stderr = await asyncio.wait_for(
            process.communicate(),
            timeout=timeout_seconds,
        )
    except asyncio.TimeoutError:
        process.kill()
        raise HTTPException(status_code=504, detail="Conversion timed out")
    except FileNotFoundError:
        raise HTTPException(
            status_code=500,
            detail="LibreOffice (soffice) is not installed. "
                   "Install it to enable Word→PDF conversion.",
        )

    if process.returncode != 0:
        msg = stderr.decode(errors="replace").strip() if stderr else "soffice failed"
        raise HTTPException(status_code=500, detail=msg)

    # Find the generated PDF
    output_path = _find_pdf_output(input_path, output_dir)
    return ConversionResult(
        output_path=output_path,
        file_name=f"{input_path.stem}.pdf",
    )


def _find_pdf_output(input_path: Path, output_dir: Path) -> Path:
    """Locate the PDF generated by LibreOffice in *output_dir*."""
    expected = f"{input_path.stem}.pdf"

    for entry in output_dir.iterdir():
        if entry.name.lower() == expected.lower():
            return entry

    # Fallback: pick any .pdf in the directory
    for entry in output_dir.iterdir():
        if entry.suffix.lower() == ".pdf":
            return entry

    raise HTTPException(status_code=500, detail="Converted PDF was not created")
